#! /bin/bash

echo Shutting down supervisord
(supervisorctl -c "~/.supervisord/supervisord.conf" stop all \
    && supervisorctl -c "~/.supervisord/supervisord.conf" shutdown \
    && echo Supervisord exited gracefully, exiting.) \
    || echo supervisord errored on exit, leaving anyway
