#! /bin/bash

{
(emacsclient -e '(kill-emacs)' && echo Shutdown Emacs server) \
   || echo Emacs server failed to stop
echo Shutting down supervisord
(supervisorctl -c ~/.supervisord/supervisord.conf stop all \
    && supervisorctl -c ~/.supervisord/supervisord.conf shutdown \
    && echo Supervisord exited gracefully, exiting.) \
    || echo supervisord errored on exit, leaving anyway
} 2>&1 | tee >(ts '[%Y-%m-%d %H:%M:%S]' >> ~/.log/kainga-exit.log)  
