#! /bin/bash

#     Kainga-conf the config to get the kainga (home) you want
#     Copyright (C) 2020 Shaun Alexander

#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.

#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.

#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>.

{
(emacsclient -e '(kill-emacs)' && echo Shutdown Emacs server) \
   || echo Emacs server failed to stop
echo Shutting down supervisord
(supervisorctl -c ~/.supervisord/supervisord.conf stop all \
    && supervisorctl -c ~/.supervisord/supervisord.conf shutdown \
    && echo Supervisord exited gracefully, exiting.) \
    || echo supervisord errored on exit, leaving anyway
} 2>&1 | tee >(ts '[%Y-%m-%d %H:%M:%S]' >> ~/.log/kainga-exit.log)  
