#! /bin/bash -i

#     Kainga-conf the config to get the kainga (home) you want
#     Copyright (C) 2020 Shaun Alexander

#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.

#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.

#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>.

echo Running Matapihi Start - installing packages
# update and install dependenices
sudo apt-get update && sudo apt-get upgrade \
    && sudo apt-get install -y python3 python3-pip git


echo Running Matapihi Start - Cloning kainga
# try a clone if it doesn't exist, if it does cd to and pull that repo
dir_bak=$(pwd)
git clone https://github.com/sierra-alpha/kainga-conf.git 2>/dev/null \
    || cd kainga-conf && git pull && cd "$dir_bak"

echo Running Matapihi Start - Pip install and run wakahiki

# Need to add python stuff to the path, and install wakahiki,
# Run wakahiki the multithreaded script runner to setup our env
export PATH="$(python3 -m site --user-base)"/bin:$PATH
pip3 install -U wakahiki

if wakahiki -c ~/kainga-conf/kainga.conf -l debug -o ~/.wakahiki.log -u $USER;
then
    echo Running Matapihi Start - launching emacs
    cd ~
    # Source the .bashrc so that we get our env before launching emacs
    . .bashrc
    # launch and dison an xTerm so we have a CLI if required
    (xterm -maximize -e "bash -i" & disown)
    # our kainga-conf starts emacs --daemon as part of its config
    # Launch emacs, after all thats why where here right ;)
    echo Warning, this is the script that is keeping the session alive,
    echo closing it will forcefully destroy the session,
    echo exit emacs with a \`ctrl-x ctrl-c\` or a \`ESC :q ENTER\` instead
    emacsclient -c
else
   echo Exiting Matapihi Start - Kainga not installed or failed to run
   exit 1
fi

